const $=s=>document.querySelector(s);let last=null;
async function post(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Erro');return j}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(s){last=s;$('#connection').classList.add('online');$('#connection span').textContent='Ligado';$('#version').textContent='v'+s.version;$('#hottest').textContent=s.hottest==null?'--':Math.round(s.hottest);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===s.mode));
  const titles={smc:['SMC Apple','Controlo original','O firmware Apple gere automaticamente as ventoinhas.'],auto:['Curva automática',s.presets[s.preset]?.label||s.preset,s.override_active?'O controlador assumiu as ventoinhas.':'Em espera; o SMC mantém o controlo.'],manual:['Controlo manual',Math.round(s.manual_percent)+'%','Velocidade definida manualmente com proteção crítica.']};const t=titles[s.mode];$('#control-pill').textContent=t[0];$('#mode-title').textContent=t[1];$('#mode-description').textContent=t[2];
  $('#preset-section').classList.toggle('hidden',s.mode!=='auto');$('#manual-section').classList.toggle('hidden',s.mode!=='manual');$('#manual-slider').value=s.manual_percent;$('#manual-value').textContent=Math.round(s.manual_percent);
  $('#profiles').innerHTML=Object.entries(s.presets).map(([k,v])=>`<button class="profile ${k===s.preset?'active':''}" data-preset="${esc(k)}"><strong>${esc(v.label)}</strong><span>${v.curve[0][0]}° → ${v.curve.at(-1)[0]}°C</span></button>`).join('');
  document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=async()=>{try{render(await post('/api/preset',{preset:b.dataset.preset}))}catch(e){alert(e.message)}});
  $('#override').textContent=s.override_active?`Controlador ativo · ${s.requested_percent??100}%`:'Gestão pelo SMC';
  $('#fans').innerHTML=s.fans.map(f=>{if(f.error)return`<div class="fan">${esc(f.label)} · erro</div>`;const pct=Math.max(0,Math.min(100,(f.rpm-f.minimum)/(f.maximum-f.minimum)*100));return`<div class="fan"><div class="fan-head"><span>${esc(f.label)}</span><span>alvo ${f.target||'SMC'}</span></div><div class="fan-rpm">${f.rpm} <small>RPM</small></div><div class="bar"><i style="width:${pct}%"></i></div></div>`}).join('');
  $('#sensors').innerHTML=s.temperatures.slice(0,8).map(x=>`<div class="sensor"><span title="${esc(x.label)}">${esc(x.label)}</span><strong>${x.celsius.toFixed(1)}°</strong></div>`).join('');
  const warning=$('#warning');warning.classList.toggle('hidden',!s.error&&s.control_available);warning.textContent=s.error||'O kernel está em modo de leitura. Reinicia depois da instalação para ativar o controlo.';
}
async function refresh(){try{const r=await fetch('/api/status',{cache:'no-store'});render(await r.json())}catch(e){$('#connection').classList.remove('online');$('#connection span').textContent='Desligado'}}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=async()=>{try{render(await post('/api/mode',{mode:b.dataset.mode}))}catch(e){alert(e.message)}});let timer;$('#manual-slider').oninput=e=>{$('#manual-value').textContent=e.target.value;clearTimeout(timer);timer=setTimeout(async()=>{try{render(await post('/api/manual',{percent:+e.target.value}))}catch(err){alert(err.message)}},180)};refresh();setInterval(refresh,1500);
